// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2WIjEUIZpU4hm36YggE7Ip01A-a4wivg',
    appId: '1:487290600199:web:9d42c811e2b5750f0de3a2',
    messagingSenderId: '487290600199',
    projectId: 'social-app-87d92',
    authDomain: 'social-app-87d92.firebaseapp.com',
    storageBucket: 'social-app-87d92.appspot.com',
    measurementId: 'G-9S49WJZC72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGELmd3N08aNGhWueWG7FfpExRR_E8Ic',
    appId: '1:487290600199:android:1d27dfe6811736550de3a2',
    messagingSenderId: '487290600199',
    projectId: 'social-app-87d92',
    storageBucket: 'social-app-87d92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQZ3mNX7HteNzyMMN_Ni6tVmffsKB8Si8',
    appId: '1:487290600199:ios:f3b139484d8a12ce0de3a2',
    messagingSenderId: '487290600199',
    projectId: 'social-app-87d92',
    storageBucket: 'social-app-87d92.appspot.com',
    iosClientId: '487290600199-cbb110vmhh34shebs2lutot2f994327a.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
